name: ki-konkret-hackathon
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - gradio>=4.0.0
  - gradio_client
  - requests
  - pyyaml
  - pip
  - pip:
    - reportlab  # Better PDF library with Unicode support
    - mistletoe
