models:
  - meta-llama-3.1-8b-instruct
  - mistral-large-instruct
  - meta-llama-3.3-70b-instruct
  - qwen2.5-72b-instruct
api_key:
  - 'YOUR_API_KEY_HERE' # Replace with your API key
base_url:
  - https://chat-ai.academiccloud.de/v1